### ISSUE TITLE
Clover 4.5.2 compiler seems to have trouble with records with generics

### ISSUE THREAD

**Issue by mebigfatguy** [openclover/clover#264] opened 2024-07-19 13:58 UTC
This syntax seems to confuse clover 4.5.2

    public class MapDifference<T, U, V> {

        public record ValueClasses<U, V>(U left, V right) {
        }
    }

 [clover] /scratch/acme/utils/MapDifference.java:3:3:expecting LPAREN, found '<'

[2024-07-19T13:55:17.920Z]    [clover] ** Error(s) occurred and the instrumentation process can't continue.}

**Comment by marek-parfianowicz** [comment] 2024-07-19 19:02
Hi Dave, thank you for reporting this problem. This is a duplicate of bug #251, fix is implemented on the `master` branch and waiting for the 5.0.0 release. I hope to release 5.0.0 till end of summer. If you can't wait so long, I recommend checking out sources and building OpenClover on your own.

**Closed by marek-parfianowicz** 2024-07-19 19:02 UTC
