### ISSUE TITLE
Istrumentation of generic instanceof pattern matching produces invalid Java code

### ISSUE THREAD

**Issue by matic277** [openclover/clover#253] opened 2024-03-19 08:01 UTC
Instrumentation produces invalid Java code, if generics are used in instanceof pattern matching.
Example:
```
public class Main
{
  public static void main(String[] args)
  {
    // ok
    final var generic = Generic.get();
    if (!(generic instanceof Generic g))
    {
      System.out.println();
    }
    else
    {
      System.out.println(g.someObj);
    }
    
    // not ok
    if (!(generic instanceof Generic<?> g))
    {
      System.out.println();
    }
    else
    {
      System.out.println(g.someObj);
    }
  }
  
  public static class Generic<T>
  {
    T someObj = null;
    
    public static Object get() { return new Generic<>(); }
  }
}
```

Produces:
```
public class Main
{public static class __CLR4_5_21b1blty2xw21{...}
  public static void main(String[] args)
  {__CLR4_5_21b1blty2xw21.R.inc(47);
    // ok
    __CLR4_5_21b1blty2xw21.R.inc(48);final var generic = Generic.get();
    __CLR4_5_21b1blty2xw21.R.inc(49);if (!(generic instanceof Generic g))
    {{
      __CLR4_5_21b1blty2xw21.R.inc(52);System.out.println();
    }
    }else
    {{
      __CLR4_5_21b1blty2xw21.R.inc(53);System.out.println(g.someObj);
    }
    
    // not ok
    }__CLR4_5_21b1blty2xw21.R.inc(54);if ((((!(generic instanceof Generic<?> g))&&(__CLR4_5_21b1blty2xw21.R.iget(55)!=0|true))||(__CLR4_5_21b1blty2xw21.R.iget(56)==0&false)))
    {{
      __CLR4_5_21b1blty2xw21.R.inc(57);System.out.println();
    }
    }else
    {{
      __CLR4_5_21b1blty2xw21.R.inc(58);System.out.println(g.someObj); // ERROR HERE, g is out of scope
    }
  }}
  
  public static class Generic<T>
  {
    T someObj = null;
    
    public static Object get() {__CLR4_5_21b1blty2xw21.R.inc(59); __CLR4_5_21b1blty2xw21.R.inc(60);return new Generic<>(); }
  }
}
```

Note how clover adds more conditions to the second if-statement, which uses generics <?> on instanceof matching.
Which I assume put the variable "g" out of scope in the else block.

Using Java 17 with OpenClover 4.5.2

**Comment by marek-parfianowicz** [comment] 2024-03-19 13:20
Thank you for reporting this. I think this is a duplicate of https://github.com/openclover/clover/issues/237, in which I fixed two problems - the "final" keyword in instanceof and the "<?>" generic signature.

**Closed** 2024-03-19 13:21 UTC
Labels: bug, resolved
