### ISSUE TITLE
Instrumentation of the instanceof pattern matching with the 'final' keyword fails

### ISSUE THREAD

**Issue by mebigfatguy** [openclover/clover#237] opened 2024-02-02 18:06 UTC
Using the new 4.5.2 version of open-clover,  using jdk17, i get errors hitting
```
    private Object loadPickerValues(Object value, FilterOperator equality, GridEOType type, FilterAvailabilityModel availabilityModel, Session session) {
        if (value == null) {
            return null;
        }

        if (equality != null && FilterOperator.IN_TYPES.contains(equality) && value instanceof final List ids) {
                .....
                .....
```
i get the error
```
unexpected token: equality
```
but i'm assuming it's the instanceof pattern matching at the end of the line

**Comment by marek-parfianowicz** [comment] 2024-02-02 22:14
PR: #238

**Comment by marek-parfianowicz** [comment] 2024-02-02 22:33
The problem is fixed now. It will wait until 4.6.0 release, unfortunately. ETA end of March. As a workaround, you can remove the 'final' keyword.

**Comment by mebigfatguy** [comment] 2024-02-02 22:41
yes it was the final attribute. good call. i can live with that. :)

**Comment by mebigfatguy** [comment] 2024-02-02 23:11
found another one. Assuming this is caused by the wildcard?

if (binding instanceof FilterableBinding<?> filterBinding) {

**Comment by marek-parfianowicz** [comment] 2024-02-02 23:33
From **java.g**:

```
        |
            (INSTANCEOF FINAL type=typeSpec IDENT) =>
            INSTANCEOF FINAL type=typeSpec IDENT
        |
            (INSTANCEOF type=typeSpec IDENT) =>
            INSTANCEOF type=typeSpec IDENT
        |
            INSTANCEOF type=typeSpec
        )
    ;
```

where typeSpec is:

```
(
            spec = classTypeSpec
        |
            spec = builtInTypeSpec
        )
```

where classTypeSpec has:

```
        typeSpec = classOrInterfaceType
        arrayOpt = arraySpecOpt
```

and finally classOrInterfaceType has:

```
        (ann=annotation)*
        IDENT
        (typeArguments)?
```

**Comment by marek-parfianowicz** [comment] 2024-02-02 23:37
Deciphering this :), the pattern matching should allow generic type arguments. Do you have instrumentation error, like previously (e.g. "unexpected token" or similar) or rather a compilation error? 

I suspect the latter one. Possibly related with the [InstanceOfState detector](https://github.com/openclover/clover/pull/238/files#diff-7149eaf3d5339506ff1c091d918325a152684faaebbc7a9541c3c49a489ef88a) I just enhanced to handle the 'final' keyword.

I believe the problem is that OpenClover added branch instrumentation to this expression, which caused that the 'filterBinding' from your example lost it's scope (not visible inside { } block).

**Comment by marek-parfianowicz** [comment] 2024-02-04 23:14
PR #240

**Comment by marek-parfianowicz** [comment] 2024-02-04 23:33
Fixed again.

**Closed by marek-parfianowicz** 2024-02-04 23:33 UTC
Labels: bug, resolved
